package io.atlas.api;
import io.atlas.api.commerce.model.CommerceModels.*;
import io.atlas.api.commerce.repository.CommerceRepository;
import io.atlas.api.commerce.service.*;
import io.atlas.api.auth.service.*;
import io.atlas.api.catalog.repository.CatalogRepository;
import io.atlas.api.shared.error.ApiFailure;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.net.*;
import java.net.http.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.test.context.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import tools.jackson.databind.ObjectMapper;
import static org.assertj.core.api.Assertions.*;
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"atlas.commerce.sales-enabled=true","atlas.core.key=isolated-test-key-never-used-outside-tests-0123456789"})
@ActiveProfiles("test")
class CommerceIntegrationTest {
 @DynamicPropertySource static void database(DynamicPropertyRegistry r){TestDatabase.properties(r);}
 @Autowired IdentityService identity;@Autowired OrderService orders;@Autowired CommerceRepository repo;@Autowired CatalogRepository catalog;@Autowired AuthService auth;@Autowired TokenCodec tokens;@Autowired JdbcTemplate db;@Autowired PasswordEncoder passwords;@Autowired ObjectMapper json;
 @LocalServerPort int port;
 UUID user,other,subject;String password;long product;
 @BeforeEach void seed(){user=UUID.randomUUID();other=UUID.randomUUID();subject=UUID.randomUUID();password=UUID.randomUUID().toString();for(var id:List.of(user,other))db.update("INSERT INTO atlas_web.users(id,username,email,password_hash,email_verified) VALUES(?,?,?,?,TRUE)",id,"Commerce test",id+"@example.invalid",passwords.encode(password));product=db.queryForObject("INSERT INTO atlas_web.products(slug,name,description,category,duration_days) VALUES(?,'VIP Test','Test','VIPs',30) RETURNING id",Long.class,"m4-"+user);db.update("INSERT INTO atlas_web.product_servers(product_id,server,price_cents,purchasable) VALUES(?,'emerald',2500,TRUE)",product);}
 @AfterEach void release(){db.update("UPDATE atlas_web.products SET active=FALSE WHERE id=?",product);db.update("UPDATE atlas_web.product_servers SET purchasable=FALSE WHERE product_id=?",product);}
 Proof proof(ChallengeCreated c,UUID player){return new Proof(c.code(),player,123,UUID.randomUUID(),"MinecraftTest","emerald");}
 LinkView link(UUID account,UUID player){var c=identity.create(account,"test");identity.prove(proof(c,player),"test");return identity.confirm(account,new Confirmation(c.id(),player),"test");}
 Checkout body(){return new Checkout(product,"emerald",1,catalog.product(product,false).revision(),catalog.revision(),2500);}
 @Test void verifiedAccountGameProofAndFinalConfirmationAreRequired(){db.update("UPDATE atlas_web.users SET email_verified=FALSE WHERE id=?",user);assertThatThrownBy(()->identity.create(user,"test")).isInstanceOf(ApiFailure.class);db.update("UPDATE atlas_web.users SET email_verified=TRUE WHERE id=?",user);var c=identity.create(user,"test");assertThat(repo.current(user)).isNull();assertThatThrownBy(()->identity.confirm(user,new Confirmation(c.id(),subject),"test")).isInstanceOf(ApiFailure.class);identity.prove(proof(c,subject),"test");assertThat(identity.status(user).pending().state()).isEqualTo("PROVED");assertThat(repo.current(user)).isNull();assertThatThrownBy(()->identity.confirm(other,new Confirmation(c.id(),subject),"test")).isInstanceOf(ApiFailure.class);assertThat(identity.confirm(user,new Confirmation(c.id(),subject),"test").subject()).isEqualTo(subject);assertThatThrownBy(()->identity.confirm(user,new Confirmation(c.id(),subject),"test")).isInstanceOf(ApiFailure.class);assertThatThrownBy(()->identity.prove(proof(c,subject),"test")).isInstanceOf(ApiFailure.class);}
 @Test void regeneratedExpiredAndUnknownCodesAreRejected(){var old=identity.create(user,"test");var current=identity.create(user,"test");assertThatThrownBy(()->identity.prove(proof(old,subject),"test")).isInstanceOf(ApiFailure.class);db.update("UPDATE atlas_web.minecraft_challenges SET expires_at=NOW()-INTERVAL '1 second' WHERE id=?",current.id());assertThatThrownBy(()->identity.prove(proof(current,subject),"test")).isInstanceOf(ApiFailure.class);assertThat(identity.status(user).pending()).isNull();assertThatThrownBy(()->identity.prove(new Proof(tokens.random(),subject,123,UUID.randomUUID(),"Test","emerald"),"test")).isInstanceOf(ApiFailure.class);}
 @Test void concurrentConfirmationsCannotBindOnePlayerToTwoAccounts()throws Exception{var a=identity.create(user,"test");var b=identity.create(other,"test");identity.prove(proof(a,subject),"test");identity.prove(proof(b,subject),"test");var pool=Executors.newFixedThreadPool(2);var go=new CountDownLatch(1);try{var x=pool.submit(()->confirm(user,a,go));var y=pool.submit(()->confirm(other,b,go));go.countDown();assertThat(List.of(x.get(10,TimeUnit.SECONDS),y.get(10,TimeUnit.SECONDS))).containsExactlyInAnyOrder(true,false);}finally{pool.shutdownNow();}}
 boolean confirm(UUID account,ChallengeCreated c,CountDownLatch go)throws Exception{go.await();try{identity.confirm(account,new Confirmation(c.id(),subject),"test");return true;}catch(ApiFailure e){return false;}}
 @Test void checkoutRetriesAndConcurrentClicksCreateOneOrder()throws Exception{link(user,subject);var input=body();var key=UUID.randomUUID().toString();var pool=Executors.newFixedThreadPool(2);var go=new CountDownLatch(1);try{Callable<OrderView> task=()->{go.await();return orders.checkout(user,key,input,"test");};var a=pool.submit(task);var b=pool.submit(task);go.countDown();assertThat(a.get(10,TimeUnit.SECONDS).id()).isEqualTo(b.get(10,TimeUnit.SECONDS).id());}finally{pool.shutdownNow();}var order=orders.checkout(user,key,input,"test");assertThat(order.snapshot().subject()).isEqualTo(subject);assertThat(orders.list(user,0).items()).hasSize(1);assertThat(orders.list(other,0).items()).isEmpty();assertThatThrownBy(()->orders.detail(other,order.id())).isInstanceOf(ApiFailure.class);assertThatThrownBy(()->orders.checkout(user,key,new Checkout(product,"emerald",1,1,catalog.revision(),2600),"test")).isInstanceOf(ApiFailure.class);assertThat(db.queryForObject("SELECT count(*) FROM atlas_web.order_events WHERE order_id=?",Integer.class,order.id())).isEqualTo(1);}
 @Test void unlinkRequiresPasswordAndKeepsHistoricRecipientAndExpiry(){var linked=link(user,subject);var input=body();var key=UUID.randomUUID().toString();var order=orders.checkout(user,key,input,"test");assertThatThrownBy(()->identity.unlink(user,new Unlink("wrong-password"),"test")).isInstanceOf(ApiFailure.class);assertThat(repo.current(user).id()).isEqualTo(linked.id());identity.unlink(user,new Unlink(password),"test");link(user,UUID.randomUUID());assertThat(orders.detail(user,order.id()).snapshot().subject()).isEqualTo(subject);assertThat(orders.checkout(user,key,input,"test").id()).isEqualTo(order.id());var later=new OrderService(repo,catalog,auth,Clock.fixed(order.expiresAt(),ZoneOffset.UTC),tokens,json,true);assertThat(later.detail(user,order.id()).paymentStatus()).isEqualTo("EXPIRED");assertThat(later.detail(user,order.id()).deliveryStatus()).isEqualTo("WAITING");}
 @Test void promotionBoundaryAndPriceChangesRequireNewConfirmation(){link(user,subject);var input=body();db.update("UPDATE atlas_web.product_servers SET price_cents=2700 WHERE product_id=?",product);assertThatThrownBy(()->orders.checkout(user,UUID.randomUUID().toString(),input,"test")).hasMessageContaining("preço");db.update("UPDATE atlas_web.product_servers SET price_cents=2500 WHERE product_id=?",product);var now=Instant.now();db.update("INSERT INTO atlas_web.promotions(product_id,server,name,original_cents,final_cents,starts_at,ends_at) VALUES(?,'emerald','Boundary',2500,2000,?,?)",product,java.sql.Timestamp.from(now),java.sql.Timestamp.from(now.plusSeconds(60)));assertThatThrownBy(()->orders.checkout(user,UUID.randomUUID().toString(),input,"test")).hasMessageContaining("preço");var order=orders.checkout(user,UUID.randomUUID().toString(),new Checkout(product,"emerald",1,1,catalog.revision(),2000),"test");assertThat(order.snapshot().promotionId()).isNotNull();assertThat(order.totalCents()).isEqualTo(2000);}
 @Test void rejectsUnlinkedUnverifiedClosedSalesInactiveProductsAndWrongDestination(){assertThatThrownBy(()->orders.checkout(user,UUID.randomUUID().toString(),body(),"test")).hasMessageContaining("Vincule");link(user,subject);db.update("UPDATE atlas_web.users SET email_verified=FALSE WHERE id=?",user);assertThatThrownBy(()->orders.checkout(user,UUID.randomUUID().toString(),body(),"test")).hasMessageContaining("email");db.update("UPDATE atlas_web.users SET email_verified=TRUE WHERE id=?",user);var closed=new OrderService(repo,catalog,auth,Clock.systemUTC(),tokens,json,false);assertThatThrownBy(()->closed.checkout(user,UUID.randomUUID().toString(),body(),"test")).hasMessageContaining("fechadas");db.update("UPDATE atlas_web.products SET active=FALSE WHERE id=?",product);assertThatThrownBy(()->orders.checkout(user,UUID.randomUUID().toString(),body(),"test")).hasMessageContaining("indisponível");db.update("UPDATE atlas_web.products SET active=TRUE WHERE id=?",product);assertThatThrownBy(()->orders.checkout(user,UUID.randomUUID().toString(),new Checkout(product,"other",1,1,catalog.revision(),2500),"test")).isInstanceOf(ApiFailure.class);assertThatThrownBy(()->orders.checkout(user,UUID.randomUUID().toString(),new Checkout(product,"emerald",2,1,catalog.revision(),2500),"test")).isInstanceOf(ApiFailure.class);assertThat(orders.list(user,0).items()).isEmpty();}
 class Browser {
  final HttpClient client=HttpClient.newBuilder().cookieHandler(new CookieManager(null,CookiePolicy.ACCEPT_ALL)).build();
  HttpResponse<String> get(String path)throws Exception{return client.send(HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1/"+path)).GET().build(),HttpResponse.BodyHandlers.ofString());}
  HttpResponse<String> post(String path,Object body,boolean csrf)throws Exception{var r=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+path)).header("Content-Type","application/json");if(csrf){var token=json.readTree(get("auth/csrf").body());r.header(token.get("headerName").asString(),token.get("token").asString());}return client.send(r.POST(HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body))).build(),HttpResponse.BodyHandlers.ofString());}
 }
 @Test void realHttpRequiresSessionCsrfAndPrivateCoreCredential()throws Exception{var b=new Browser();assertThat(b.get("orders").statusCode()).isEqualTo(401);assertThat(b.get("users/me/minecraft-link").statusCode()).isEqualTo(401);assertThat(b.post("/api/v1/auth/login",Map.of("email",user+"@example.invalid","password",password),true).statusCode()).isEqualTo(200);assertThat(b.post("/api/v1/users/me/minecraft-link-challenges",Map.of(),false).statusCode()).isEqualTo(403);var c=identity.create(user,"test");assertThat(b.post("/internal/v1/minecraft/proofs",proof(c,subject),false).statusCode()).isEqualTo(403);assertThat(b.post("/api/v1/users/me/minecraft-link-confirmations",new Confirmation(c.id(),subject),true).statusCode()).isEqualTo(409);var request=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/internal/v1/minecraft/proofs")).header("X-Atlas-Key","isolated-test-key-never-used-outside-tests-0123456789").header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(json.writeValueAsString(proof(c,subject)))).build();assertThat(b.client.send(request,HttpResponse.BodyHandlers.ofString()).statusCode()).isEqualTo(204);assertThat(b.post("/api/v1/users/me/minecraft-link-confirmations",new Confirmation(c.id(),subject),true).statusCode()).isEqualTo(200);}
}
