ALTER TABLE homes
    ALTER COLUMN player_id SET NOT NULL,
    ALTER COLUMN name SET NOT NULL,
    ALTER COLUMN world SET NOT NULL,
    ALTER COLUMN x SET NOT NULL,
    ALTER COLUMN y SET NOT NULL,
    ALTER COLUMN z SET NOT NULL,
    ALTER COLUMN yaw SET NOT NULL,
    ALTER COLUMN pitch SET NOT NULL;

ALTER TABLE homes
    ADD COLUMN IF NOT EXISTS is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS idx_homes_player_name
ON homes(player_id, LOWER(name));

CREATE INDEX IF NOT EXISTS idx_homes_player_primary
ON homes(player_id, is_primary);
