########################################
# Atlas Configuration
########################################

#====================================================
# SERVER
#====================================================

SERVER_NAME="Atlas"

SERVER_PATH="/opt/atlas/server"
FABRIC_PATH="/opt/atlas/server/fabric"
MODS_PATH="/opt/atlas/server/fabric/mods"
BACKUP_PATH="/opt/atlas/server/backups"

LOG_PATH="/opt/atlas/server/logs"

WORLD_PATH="/opt/atlas/server/worlds"

SERVER_PORT="25565"

MAX_PLAYERS="50"

ONLINE_MODE="false"

MOTD="Atlas Cobblemon"

#====================================================
# JAVA
#====================================================

JAVA_VERSION="21"

JAVA_MIN_MEMORY="2G"

JAVA_MAX_MEMORY="6G"

#====================================================
# MINECRAFT
#====================================================

MC_VERSION="1.21.1"

FABRIC_LOADER_VERSION="0.17.3"

FABRIC_INSTALLER_VERSION="1.0.3"

COBBLEMON_VERSION="1.7.3"

VIEW_DISTANCE="10"

SIMULATION_DISTANCE="10"

ALLOW_FLIGHT="true"

ENABLE_COMMAND_BLOCK="true"

#====================================================
# DATABASE
#====================================================

POSTGRES_HOST="localhost"

POSTGRES_PORT="5432"

POSTGRES_DATABASE="atlas"

POSTGRES_USER="atlas"

POSTGRES_PASSWORD="atlas"

#====================================================
# BACKUP
#====================================================

BACKUP_DAYS="30"

BACKUP_INTERVAL="24h"