########################################
# Atlas Stack
########################################

STACK_NAME="Atlas Cobblemon Stack"

FABRIC_API_SLUG="fabric-api"
COBBLEMON_SLUG="cobblemon"
LITHIUM_SLUG="lithium"
FERRITECORE_SLUG="ferrite-core"
MODERNFIX_SLUG="modernfix"