package io.atlas.api.delivery;
import io.atlas.api.delivery.DeliveryModels.*;
import io.atlas.api.commerce.model.CommerceModels.Snapshot;
import org.springframework.stereotype.Repository;
import org.springframework.jdbc.core.JdbcTemplate;
import tools.jackson.databind.ObjectMapper;
import java.time.Instant;
import java.sql.Timestamp;
import java.util.*;
@Repository
public class DeliveryRepository {
 private final JdbcTemplate db;private final ObjectMapper json;
 public DeliveryRepository(JdbcTemplate db,ObjectMapper json){this.db=db;this.json=json;}
 public record Row(UUID id,UUID orderId,String state,UUID token,Instant leaseUntil,String paymentStatus,Snapshot snapshot,String mode,int attempts,Receipt receipt){}
 private Row row(java.sql.ResultSet r)throws java.sql.SQLException{return new Row(r.getObject("id",UUID.class),r.getObject("order_id",UUID.class),r.getString("state"),r.getObject("lease_token",UUID.class),r.getTimestamp("lease_until")==null?null:r.getTimestamp("lease_until").toInstant(),r.getString("payment_status"),json.readValue(r.getString("snapshot"),Snapshot.class),r.getString("mode"),r.getInt("attempts"),r.getString("receipt")==null?null:json.readValue(r.getString("receipt"),Receipt.class));}
 private static final String SELECT="SELECT d.*,o.payment_status,o.snapshot,p.mode FROM atlas_web.delivery_outbox d JOIN atlas_web.orders o ON o.id=d.order_id JOIN atlas_web.payment_attempts p ON p.order_id=o.id ";
 public Row lock(UUID id){return db.query(SELECT+"WHERE d.id=? FOR UPDATE OF o,d",(r,n)->row(r),id).stream().findFirst().orElse(null);}
 public List<Row> claim(String mode,Instant now){
  db.update("WITH held AS (UPDATE atlas_web.delivery_outbox SET state='REVIEW',last_error='RETRY_LIMIT' WHERE state='WAITING' AND attempts>=8 AND (lease_until IS NULL OR lease_until<=?) RETURNING order_id) UPDATE atlas_web.orders SET delivery_status='REVIEW' WHERE id IN(SELECT order_id FROM held)",Timestamp.from(now));
  var rows=db.query(SELECT+"WHERE d.state='WAITING' AND o.payment_status='PAID' AND p.mode=? AND o.snapshot->>'server'='emerald' AND d.attempts<8 AND d.next_attempt<=? AND (d.lease_until IS NULL OR d.lease_until<=?) ORDER BY d.next_attempt,d.id LIMIT 10 FOR UPDATE OF d SKIP LOCKED",(r,n)->row(r),mode,Timestamp.from(now),Timestamp.from(now));
  List<Row> claimed=new ArrayList<>();for(var r:rows){UUID token=UUID.randomUUID();Instant until=now.plusSeconds(120);db.update("UPDATE atlas_web.delivery_outbox SET lease_token=?,lease_until=?,attempts=attempts+1,next_attempt=? WHERE id=?",token,Timestamp.from(until),Timestamp.from(now.plusSeconds(Math.min(3600,10L<<Math.min(r.attempts(),8)))),r.id());claimed.add(new Row(r.id(),r.orderId(),r.state(),token,until,r.paymentStatus(),r.snapshot(),r.mode(),r.attempts()+1,r.receipt()));}return claimed;
 }
 public void review(Row r,String code,Instant now){db.update("UPDATE atlas_web.delivery_outbox SET state='REVIEW',last_error=?,lease_until=NULL,lease_token=NULL WHERE id=?",code,r.id());db.update("UPDATE atlas_web.orders SET delivery_status='REVIEW' WHERE id=?",r.orderId());audit(r.id(),null,"REVIEW",code,now);}
 public void fail(Row r,String code,Instant now){db.update("UPDATE atlas_web.delivery_outbox SET last_error=?,lease_until=NULL,lease_token=NULL,next_attempt=? WHERE id=?",code,Timestamp.from(now.plusSeconds(Math.min(3600,10L<<Math.min(r.attempts(),8)))),r.id());}
 public void delivered(Row r,Ack ack,Instant now){db.update("UPDATE atlas_web.delivery_outbox SET state='DELIVERED',receipt=?::jsonb,ack_token=?,lease_until=NULL,last_error=NULL WHERE id=?",json.writeValueAsString(ack.receipt()),ack.leaseToken(),r.id());db.update("UPDATE atlas_web.orders SET delivery_status='DELIVERED' WHERE id=?",r.orderId());db.update("INSERT INTO atlas_web.order_events(order_id,event,request_id,created_at) VALUES(?,'DELIVERY_CONFIRMED',?,?)",r.orderId(),r.id().toString(),Timestamp.from(now));audit(r.id(),null,"DELIVERED","Core receipt committed",now);}
 public void mirror(Balance b,Instant now){db.update("INSERT INTO atlas_web.vip_mirrors(subject,core_player_id,server,vip1_ms,vip2_ms,vip3_ms,checkpoint,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(subject) DO UPDATE SET vip1_ms=excluded.vip1_ms,vip2_ms=excluded.vip2_ms,vip3_ms=excluded.vip3_ms,checkpoint=excluded.checkpoint,updated_at=excluded.updated_at WHERE vip_mirrors.core_player_id=excluded.core_player_id AND vip_mirrors.server=excluded.server AND vip_mirrors.checkpoint<excluded.checkpoint",b.subject(),b.corePlayerId(),b.server(),b.vip1Ms(),b.vip2Ms(),b.vip3Ms(),Timestamp.from(b.checkpoint()),Timestamp.from(now));}
 public boolean known(Balance b){return Boolean.TRUE.equals(db.queryForObject("SELECT EXISTS(SELECT 1 FROM atlas_web.minecraft_links WHERE subject=? AND core_player_id=? AND server=?)",Boolean.class,b.subject(),b.corePlayerId(),b.server()));}
 public VipView vip(UUID user,Instant now){var linked=db.queryForList("SELECT subject FROM atlas_web.minecraft_links WHERE user_id=? AND revoked_at IS NULL",user);if(linked.isEmpty())return DeliveryModels.view(false,null,now);var b=db.query("SELECT * FROM atlas_web.vip_mirrors WHERE subject=?",(r,n)->new Balance(r.getObject("subject",UUID.class),r.getLong("core_player_id"),r.getString("server"),r.getLong("vip1_ms"),r.getLong("vip2_ms"),r.getLong("vip3_ms"),r.getTimestamp("checkpoint").toInstant()),linked.getFirst().get("subject"));return DeliveryModels.view(true,b.isEmpty()?null:b.getFirst(),now);}
 public List<Attempt> attempts(int page){return db.query("SELECT d.*,o.snapshot->>'nickname' nickname FROM atlas_web.delivery_outbox d JOIN atlas_web.orders o ON o.id=d.order_id ORDER BY d.created_at DESC,d.id LIMIT 21 OFFSET ?",(r,n)->new Attempt(r.getObject("id",UUID.class),r.getObject("order_id",UUID.class),r.getString("nickname"),r.getString("state"),r.getInt("attempts"),r.getTimestamp("lease_until")==null?null:r.getTimestamp("lease_until").toInstant(),r.getTimestamp("next_attempt").toInstant(),r.getString("last_error"),r.getTimestamp("created_at").toInstant()),page*20);}
 public void retry(Row r,UUID actor,String reason,Instant now){db.update("UPDATE atlas_web.delivery_outbox SET state='WAITING',attempts=0,next_attempt=?,lease_until=NULL,lease_token=NULL,last_error=NULL WHERE id=?",Timestamp.from(now),r.id());db.update("UPDATE atlas_web.orders SET delivery_status='PROCESSING' WHERE id=?",r.orderId());audit(r.id(),actor,"REPROCESS",reason,now);}
 private void audit(UUID id,UUID actor,String action,String reason,Instant now){db.update("INSERT INTO atlas_web.delivery_audit(delivery_id,actor,action,reason,created_at) VALUES(?,?,?,?,?)",id,actor,action,reason,Timestamp.from(now));}
}
