CREATE TABLE atlas_web.catalog_state (id INTEGER PRIMARY KEY CHECK(id=1), revision BIGINT NOT NULL DEFAULT 1);
INSERT INTO atlas_web.catalog_state(id) VALUES(1);
CREATE TABLE atlas_web.servers (slug TEXT PRIMARY KEY, active BOOLEAN NOT NULL DEFAULT TRUE);
INSERT INTO atlas_web.servers VALUES('emerald',TRUE);
CREATE TABLE atlas_web.products (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK(id BETWEEN 1 AND 9007199254740991),
 slug VARCHAR(80) UNIQUE NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(2000) NOT NULL,
 category VARCHAR(20) NOT NULL CHECK(category IN ('VIPs','Chaves','Pacotes','Cosméticos')),
 active BOOLEAN NOT NULL DEFAULT TRUE, revision BIGINT NOT NULL DEFAULT 1,
 duration_days INTEGER NOT NULL DEFAULT 30 CHECK(duration_days=30)
);
CREATE TABLE atlas_web.product_servers (
 product_id BIGINT REFERENCES atlas_web.products(id), server TEXT REFERENCES atlas_web.servers(slug),
 price_cents INTEGER NOT NULL CHECK(price_cents BETWEEN 1 AND 100000000),
 active BOOLEAN NOT NULL DEFAULT TRUE,
 purchasable BOOLEAN NOT NULL DEFAULT FALSE CHECK(purchasable=FALSE), PRIMARY KEY(product_id,server)
);
INSERT INTO atlas_web.products(slug,name,description,category) VALUES
 ('vip-1','VIP 1','O primeiro passo para sua jornada.','VIPs'),
 ('vip-2','VIP 2','Mais possibilidades para sua equipe.','VIPs'),
 ('vip-3','VIP 3','A experiência completa dos kits VIP.','VIPs');
INSERT INTO atlas_web.product_servers SELECT id,'emerald',CASE slug WHEN 'vip-1' THEN 2500 WHEN 'vip-2' THEN 3500 ELSE 5000 END,TRUE,FALSE FROM atlas_web.products;
CREATE TABLE atlas_web.promotions (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY CHECK(id BETWEEN 1 AND 9007199254740991),
 product_id BIGINT NOT NULL, server TEXT NOT NULL,
 name VARCHAR(100) NOT NULL, original_cents INTEGER NOT NULL CHECK(original_cents>0),
 final_cents INTEGER NOT NULL CHECK(final_cents>0 AND final_cents<original_cents),
 discount_basis_points INTEGER CHECK(discount_basis_points BETWEEN 1 AND 9999),
 starts_at TIMESTAMPTZ NOT NULL, ends_at TIMESTAMPTZ NOT NULL CHECK(ends_at>starts_at),
 terminal_status TEXT CHECK(terminal_status IN ('CANCELLED','FINISHED')),
 revision BIGINT NOT NULL DEFAULT 1,
 FOREIGN KEY(product_id,server) REFERENCES atlas_web.product_servers(product_id,server)
);
CREATE INDEX promotions_lookup ON atlas_web.promotions(product_id,server,starts_at,ends_at) WHERE terminal_status IS NULL;
-- All promotion writers serialize through the offer's product row; this trigger
-- also enforces exclusion for direct SQL and independent application instances.
CREATE FUNCTION atlas_web.prevent_promotion_overlap() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 PERFORM 1 FROM atlas_web.products WHERE id=NEW.product_id FOR UPDATE;
 IF NEW.terminal_status IS NULL AND EXISTS(SELECT 1 FROM atlas_web.promotions p WHERE p.id<>NEW.id AND p.product_id=NEW.product_id AND p.server=NEW.server AND p.terminal_status IS NULL AND tstzrange(p.starts_at,p.ends_at,'[)') && tstzrange(NEW.starts_at,NEW.ends_at,'[)')) THEN
  RAISE EXCEPTION 'Promotion overlap' USING ERRCODE='23P01';
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER promotions_no_overlap BEFORE INSERT OR UPDATE ON atlas_web.promotions FOR EACH ROW EXECUTE FUNCTION atlas_web.prevent_promotion_overlap();
CREATE TABLE atlas_web.catalog_audit (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, actor UUID REFERENCES atlas_web.users(id),
 action TEXT NOT NULL, resource TEXT NOT NULL, before_data JSONB, after_data JSONB,
 request_id VARCHAR(100) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE atlas_web.product_versions (
 product_id BIGINT REFERENCES atlas_web.products(id), revision BIGINT NOT NULL,
 snapshot JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(product_id,revision)
);
INSERT INTO atlas_web.product_versions SELECT p.id,p.revision,to_jsonb(p)||jsonb_build_object('priceCents',s.price_cents,'server',s.server) FROM atlas_web.products p JOIN atlas_web.product_servers s ON p.id=s.product_id;
GRANT SELECT,INSERT,UPDATE ON atlas_web.products,atlas_web.product_servers,atlas_web.promotions TO atlas_api_runtime;
GRANT SELECT,UPDATE ON atlas_web.catalog_state TO atlas_api_runtime;
GRANT SELECT ON atlas_web.servers TO atlas_api_runtime;
GRANT SELECT,INSERT ON atlas_web.catalog_audit,atlas_web.product_versions TO atlas_api_runtime;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA atlas_web TO atlas_api_runtime;
UPDATE atlas_web.system_metadata SET schema_generation=3 WHERE id=1;
